name: phone_store
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  gap: ^3.0.1 
  line_awesome_flutter: ^2.0.0
  shared_preferences: ^2.2.2
  intl_phone_field: ^3.1.0
  pin_code_fields: ^8.0.1
  path_provider: ^2.0.2
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.22.0
  image_picker: ^0.8.4+2 
  carousel_slider: ^4.2.1
  read_more_text: ^0.0.5
  url_launcher: ^6.2.5
  http: ^1.2.1
  # state management
  flutter_riverpod: ^2.5.1
  jwt_decoder: ^2.0.1
  dio: ^5.4.2+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.0
  connectivity_plus: ^6.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/
  #   - images/a_dot_ham.jpeg
